cask_args appdir: "/Applications"

# Core shell/dev tooling
brew "bat"
brew "curl"
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "jq"
brew "mise"
brew "mole"
brew "ripgrep"
brew "shellcheck"
brew "stow"
brew "thefuck"
brew "tmux"
brew "tree"
brew "wget"
brew "zoxide"

# Common apps. Keep this list intentionally small and non-sensitive.
cask "google-chrome"
cask "orbstack"
